### ISSUE TITLE
Exception when Launching Chrome, after it crashed.

### ISSUE THREAD

**Issue by FlameDuck** [kklisura/chrome-devtools-java-client#15]
I'm not really sure how to reproduce this, but I suspect that what is happening is something like this:

Process launches.
Pages are loaded.
Chrome Crashes.
Another page is trying to load:

This happens:

    java.lang.IllegalArgumentException: Hook previously registered
        at java.base/java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:72) ~[na:na]
        at java.base/java.lang.Runtime.addShutdownHook(Runtime.java:215) ~[na:na]
        at com.github.kklisura.cdt.launch.ChromeLauncher$ShutdownHookRegistry.register(ChromeLauncher.java:445) ~[cdt-java-client-1.3.3.jar:na]
        at com.github.kklisura.cdt.launch.ChromeLauncher.launchChromeProcess(ChromeLauncher.java:283) ~[cdt-java-client-1.3.3.jar:na]
        at com.github.kklisura.cdt.launch.ChromeLauncher.launch(ChromeLauncher.java:143) ~[cdt-java-client-1.3.3.jar:na]
        at com.github.kklisura.cdt.launch.ChromeLauncher.launch(ChromeLauncher.java:157) ~[cdt-java-client-1.3.3.jar:na]

Previous to that, the following happened:
    java.lang.IllegalStateException: The connection has been closed.
        at org.glassfish.tyrus.core.TyrusSession.checkConnectionState(TyrusSession.java:530) ~[tyrus-core-1.13.1.jar:na]
        at org.glassfish.tyrus.core.TyrusSession.getBasicRemote(TyrusSession.java:212) ~[tyrus-core-1.13.1.jar:na]
        at com.github.kklisura.cdt.services.impl.WebSocketServiceImpl.send(WebSocketServiceImpl.java:114) ~[cdt-java-client-1.3.3.jar:na]
        at com.github.kklisura.cdt.services.impl.ChromeDevToolsServiceImpl.invoke(ChromeDevToolsServiceImpl.java:135) ~[cdt-java-client-1.3.3.jar:na]
        at com.github.kklisura.cdt.services.invocation.CommandInvocationHandler.invoke(CommandInvocationHandler.java:80) ~[cdt-java-client-1.3.3.jar:na]
        at com.sun.proxy.$Proxy122.getResourceTree(Unknown Source) ~[na:na]

After these two exceptions have been thrown the application must be restarted to recover.

**Comment by dduda2894** [comment]
Hey there,

`java.lang.IllegalArgumentException: Hook previously registered` - The issue here is that when ChromeLauncher is initialised its  hard coded member _shutdownHook_ is initialised too and later, when launch() method is called, is registered with _shutdownHookRegistry_. When chrome crash and you try to launch chrome with the same instance of  chromeLauncher that you used to launch chrome that crashed, it tries to register the exact same shutdownHook and throws an exception. 

The workaround here is to create a new ChromeLauncher instance every time chrome crash. A new shutdown hook will be initialised and registered and you will get no error when launching chrome. 

However this workaround raises a concern that JVM will eventually run out of memory if you will continue to register shutdown hooks infinitely.
