### ISSUE TITLE
exception when running on Mac / Ubuntu 

### ISSUE THREAD

**Issue by martinbe1io** [kklisura/chrome-devtools-java-client#45]
hi, hope anybody out there can help me with my first trial of the DevTools client on java. Unfortunately I'm not familiar with AccessController Classes - I get the following exception (moreless 1:1 the example on the page)

Thanks a lot 
Martin

```
try {
			launcher = new ChromeLauncher();
			// Launch chrome either as headless (true) or regular (false).
			ChromeArguments args=null;
			if (browserparameters!=null&&browserparameters.size()>0)
			{
				args=ChromeArguments.defaults(false).additionalArguments(browserparameters).build();
				
			}else args=ChromeArguments.defaults(false).build();
			
			log.info("launcher args={} isalive={}",args,launcher.isAlive());
		    
		    chromeService = launcher.launch(args);
		    log.info("chromservice version={}",chromeService.getVersion());
		    // Create empty tab ie about:blank.
		    ChromeTab tab = chromeService.createTab();

		    // Get DevTools service to this tab
		    devToolsService = chromeService.createDevToolsService(tab);

		}  catch (Exception e) {
			StringWriter errors = new StringWriter();
			e.printStackTrace(new PrintWriter(errors));
			log.error("exception e: {} s: {}", e, errors);
			this.setAppstate(AppState.AS_ERROR);
			this.setLasterrormsg(e.toString());
		}
```

I'm using MacOS but same occurs if I run the app on ubuntu. Maybe relevant: in both ways I'm non root. 

```
[2020-07-23 07:23:52,317]-[Grizzly(1)] INFO  com.github.kklisura.cdt.services.impl.WebSocketServiceImpl - Connected to ws ws://localhost:59668/devtools/page/C2468662CE12D1DCC3790331D02EA3AE
[2020-07-23 07:23:52,341]-[netty task-4-2] ERROR com.github.kklisura.cdt.services.utils.ProxyUtils - Failed creating proxy from abstract class
java.lang.NullPointerException: null
	at io.be1.quattro//javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103)
	at io.be1.quattro//javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151)
	at io.be1.quattro//javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134)
	at io.be1.quattro//javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95)
	at io.be1.quattro//javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:131)
	at io.be1.quattro//javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:530)
	at io.be1.quattro//javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:515)
	at io.be1.quattro//javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:451)
	at io.be1.quattro//javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:422)
	at io.be1.quattro//javassist.util.proxy.ProxyFactory.create(ProxyFactory.java:698)
	at io.be1.quattro//javassist.util.proxy.ProxyFactory.create(ProxyFactory.java:683)
	at io.be1.quattro//com.github.kklisura.cdt.services.utils.ProxyUtils.createProxyFromAbstract(ProxyUtils.java:76)
	at io.be1.quattro//com.github.kklisura.cdt.services.impl.ChromeServiceImpl.createDevToolsService(ChromeServiceImpl.java:186)
	at io.be1.quattro//com.github.kklisura.cdt.services.impl.ChromeServiceImpl.createDevToolsService(ChromeServiceImpl.java:161)
	at io.be1.quattro//io.be1.quattro.digitalsignage.DigitalSignage.initComponents(DigitalSignage.java:550)
	at io.be1.quattro//io.be1.quattro.digitalsignage.DigitalSignage.start(DigitalSignage.java:187)
	at io.be1.quattro//io.be1.quattro.AppManager.initializeApp(AppManager.java:395)
	at io.be1.quattro//io.be1.quattro.AppManager.lambda$configure$5(AppManager.java:491)
	at io.be1.quattro//org.jooby.Route$Handler.handle(Route.java:1760)
	at io.be1.quattro//org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at io.be1.quattro//org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at io.be1.quattro//org.jooby.Route$Chain.next(Route.java:2163)
	at io.be1.quattro//org.jooby.Route$After.handle(Route.java:2002)
	at io.be1.quattro//org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at io.be1.quattro//org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at io.be1.quattro//org.jooby.Route$Chain.next(Route.java:2163)
	at io.be1.quattro//org.jooby.internal.pac4j2.Pac4jGrantAccessAdapter.adapt(Pac4jGrantAccessAdapter.java:224)
	at io.be1.quattro//org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:142)
	at io.be1.quattro//org.jooby.internal.pac4j2.Pac4jSecurityFilter.handle(Pac4jSecurityFilter.java:257)
	at io.be1.quattro//org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at io.be1.quattro//org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at io.be1.quattro//org.jooby.Route$Chain.next(Route.java:2163)
	at io.be1.quattro//org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)
	at io.be1.quattro//org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:274)
	at io.be1.quattro//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.be1.quattro//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.be1.quattro//io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56)
	at io.be1.quattro//io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365)
	at io.be1.quattro//io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.be1.quattro//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.be1.quattro//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.be1.quattro//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
[2020-07-23 07:23:52,342]-[netty task-4-2] ERROR io.be1.quattro.digitalsignage.DigitalSignage - exception e: java.lang.RuntimeException: Failed creating proxy from abstract class s: java.lang.RuntimeException: Failed creating proxy from abstract class
	at io.be1.quattro//com.github.kklisura.cdt.services.utils.ProxyUtils.createProxyFromAbstract(ProxyUtils.java:82)
	at io.be1.quattro//com.github.kklisura.cdt.services.impl.ChromeServiceImpl.createDevToolsService(ChromeServiceImpl.java:186)
	at io.be1.quattro//com.github.kklisura.cdt.services.impl.ChromeServiceImpl.createDevToolsService(ChromeServiceImpl.java:161)
	at io.be1.quattro//io.be1.quattro.digitalsignage.DigitalSignage.initComponents(DigitalSignage.java:550)
	at io.be1.quattro//io.be1.quattro.digitalsignage.DigitalSignage.start(DigitalSignage.java:187)
	at io.be1.quattro//io.be1.quattro.AppManager.initializeApp(AppManager.java:395)
	at io.be1.quattro//io.be1.quattro.AppManager.lambda$configure$5(AppManager.java:491)
	at io.be1.quattro//org.jooby.Route$Handler.handle(Route.java:1760)
	at io.be1.quattro//org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at io.be1.quattro//org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at io.be1.quattro//org.jooby.Route$Chain.next(Route.java:2163)
	at io.be1.quattro//org.jooby.Route$After.handle(Route.java:2002)
	at io.be1.quattro//org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at io.be1.quattro//org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at io.be1.quattro//org.jooby.Route$Chain.next(Route.java:2163)
	at io.be1.quattro//org.jooby.internal.pac4j2.Pac4jGrantAccessAdapter.adapt(Pac4jGrantAccessAdapter.java:224)
	at io.be1.quattro//org.pac4j.core.engine.DefaultSecurityLogic.perform(DefaultSecurityLogic.java:142)
	at io.be1.quattro//org.jooby.internal.pac4j2.Pac4jSecurityFilter.handle(Pac4jSecurityFilter.java:257)
	at io.be1.quattro//org.jooby.internal.RouteImpl.handle(RouteImpl.java:280)
	at io.be1.quattro//org.jooby.internal.RouteChain.next(RouteChain.java:262)
	at io.be1.quattro//org.jooby.Route$Chain.next(Route.java:2163)
	at io.be1.quattro//org.jooby.internal.HttpHandlerImpl.handle(HttpHandlerImpl.java:496)
	at io.be1.quattro//org.jooby.internal.netty.NettyHandler.channelRead0(NettyHandler.java:274)
	at io.be1.quattro//io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.be1.quattro//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.be1.quattro//io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:56)
	at io.be1.quattro//io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:365)
	at io.be1.quattro//io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66)
	at io.be1.quattro//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.be1.quattro//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.be1.quattro//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException
	at io.be1.quattro//javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103)
	at io.be1.quattro//javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151)
	at io.be1.quattro//javassist.util.proxy.DefineClassHelper.toClass2(DefineClassHelper.java:134)
	at io.be1.quattro//javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:95)
	at io.be1.quattro//javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:131)
	at io.be1.quattro//javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:530)
	at io.be1.quattro//javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:515)
	at io.be1.quattro//javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:451)
	at io.be1.quattro//javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:422)
	at io.be1.quattro//javassist.util.proxy.ProxyFactory.create(ProxyFactory.java:698)
	at io.be1.quattro//javassist.util.proxy.ProxyFactory.create(ProxyFactory.java:683)
	at io.be1.quattro//com.github.kklisura.cdt.services.utils.ProxyUtils.createProxyFromAbstract(ProxyUtils.java:76)
	... 31 more
```

**Comment by martinbe1io** [comment]
same here any solution for this ?
