### ISSUE TITLE
Update protocol failure

### ISSUE THREAD

**Issue by dannygonzalez** [kklisura/chrome-devtools-java-client#53]
I have followed your instructions on [downloading latest protocol](https://github.com/kklisura/chrome-devtools-java-client#download-latest-protocol) and [updating the protocol](https://github.com/kklisura/chrome-devtools-java-client#update-protocol-generate-java-files-from-protocol-definitions).

I am seeing the following errors when performing `make update-protocol`

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/lang/UnknownError could not be instrumented.
	at org.jacoco.agent.rt.internal_290345e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:139)
	at org.jacoco.agent.rt.internal_290345e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:100)
	at org.jacoco.agent.rt.internal_290345e.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_290345e.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:1999)
	at org.jacoco.agent.rt.internal_290345e.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:137)
	... 9 more
FATAL ERROR in native method: processing of -javaagent failed
/bin/sh: line 1: 88784 Abort trap: 6           /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java -javaagent:/Users/danny/.m2/repository/org/jacoco/org.jacoco.agent/0.8.0/org.jacoco.agent-0.8.0-runtime.jar=destfile=/Users/danny/Desktop/chrome-devtools-java-client/cdt-java-protocol-builder/target/jacoco.exec -jar /Users/danny/Desktop/chrome-devtools-java-client/cdt-java-protocol-builder/target/surefire/surefirebooter6850608009943420711.jar /Users/danny/Desktop/chrome-devtools-java-client/cdt-java-protocol-builder/target/surefire/surefire11171973420015458850tmp /Users/danny/Desktop/chrome-devtools-java-client/cdt-java-protocol-builder/target/surefire/surefire_14730910830068431712tmp

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ctd-java-client-root 1.0-SNAPSHOT .................. SUCCESS [  0.207 s]
[INFO] cdt-protocol-parser 1.0-SNAPSHOT ................... SUCCESS [  5.678 s]
[INFO] cdt-java-protocol-builder 1.0-SNAPSHOT ............. FAILURE [  4.926 s]
[INFO] cdt-java-client 3.0.0-SNAPSHOT ..................... SKIPPED
[INFO] cdt-examples 1.0-SNAPSHOT .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.019 s
[INFO] Finished at: 2020-12-04T10:48:01Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project cdt-java-protocol-builder: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :cdt-java-protocol-builder
make: *** [build-all-modules] Error 1
```

**Comment by dannygonzalez** [comment]
Just an update, I got it working by updating the Jacoco version to 0.8.6 in pom.xml.
Also I had to use Java 8 rather that Java 11 to run the update scripts.
