### ISSUE TITLE
CDT not handling Preflight InitiatorType/ResourceType

### ISSUE THREAD

**Issue by VinayBerry** [kklisura/chrome-devtools-java-client#60]
I started getting this error popping up often while handling network events.  Seems to be a new InitiatorType/ResourceType thats not currently handled by the current code.

```
Error while processing event Network.requestWillBeSent
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.github.kklisura.cdt.protocol.types.network.InitiatorType` from String "preflight": value not one of declared Enum instance names: [other, preload, script, SignedExchange, parser]
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.github.kklisura.cdt.protocol.events.network.RequestWillBeSent["initiator"]->com.github.kklisura.cdt.protocol.types.network.Initiator["type"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1535)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:910)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1608)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1292)
	at com.github.kklisura.cdt.services.impl.ChromeDevToolsServiceImpl.readJsonObject(ChromeDevToolsServiceImpl.java:355)
	at com.github.kklisura.cdt.services.impl.ChromeDevToolsServiceImpl.lambda$handleEvent$1(ChromeDevToolsServiceImpl.java:303)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
```
Error while processing event Network.responseReceived
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.github.kklisura.cdt.protocol.types.network.ResourceType` from String "Preflight": value not one of declared Enum instance names: [XHR, Media, WebSocket, Script, Stylesheet, Manifest, Other, Ping, EventSource, CSPViolationReport, Fetch, Document, TextTrack, SignedExchange, Font, Image]
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.github.kklisura.cdt.protocol.events.network.ResponseReceived["type"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1535)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:910)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:255)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:179)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1608)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1292)
	at com.github.kklisura.cdt.services.impl.ChromeDevToolsServiceImpl.readJsonObject(ChromeDevToolsServiceImpl.java:355)
	at com.github.kklisura.cdt.services.impl.ChromeDevToolsServiceImpl.lambda$handleEvent$1(ChromeDevToolsServiceImpl.java:303)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by sinaa** [comment]
This should be solved by an update on the protocol in PR #62
